### ISSUE TITLE
crossref author id to orcid id? 

### ISSUE THREAD

**Issue by cboettig** [datacite/bolognese#10]
Hi @mfenner,

Quick question: Is there a way to map from the crossref author ids I get back in the crossref xml into ORCIDs (assuming the author has an orcid)?  Do any crossref cn types return ORCID id data for articles?  Thanks!

**Comment by mfenner** [comment]
How do you get the Crossref XML? I do it like this: http://www.crossref.org/openurl/?format=unixref&id=doi:10.1101/097196&noredirect=true&pid=tech@datacite.org

You get the same XML in DOI content negotiation. You can see lots of ORCID IDs in the XML.

**Comment by cboettig** [comment]
@mfenner thanks, I guess for the few records I have tried so far the journals must not have reported author ORCIDs to crossref.  Yup, I'm doing the content negotiation; interestingly while I get no identifier in `application/vnd.crossref.unixref+xml`, it was in the `rdf+xml` that I was seeing crossref author ids, though maybe these are just arbitrary strings for the sake of RDF since they don't resolve (haven't tried confirming that the same author always gets same or different strings), e.g. 

```
"http://id.crossref.org/contributor/carl-boettiger-2cpdpe14dquid"
```

anyway, good to know the orcids are returned when they exist.  Looks like the rdf form still uses these `id.crossref.org` as the `about` `id`, but includes the ORCIDS with an `owl:sameAs`.
