### ISSUE TITLE
Allow pre-1.0 versions of thor

### ISSUE THREAD

**Issue by cjcolvar** [datacite/bolognese#101]
I'm wanting to use `bolognese` for crosswalking my data to/from datacite xml (and possibly other formats) but can't because other dependencies I have don't allow `thor` 1.0+ yet.  All of the tests still pass with `thor` 0.19 when I run them locally.  Would it be possible to allow pre-1.0 versions of `thor`?  Maybe `gem 'thor', '>= 0.19'` could work?

**Comment by mfenner** [comment]
@cjcolvar that makes sense. Do you want to do a pull request, or do you want me to do the change - assuming I don't discover any surprises?

**Comment by mfenner** [comment]
Sorry, I see that you just opened the pull request.
