### ISSUE TITLE
Sandbox Orcid URLs are not allowed. 

### ISSUE THREAD

**Issue by prdanelli** [datacite/bolognese#120]
Currently, the `Bolognese::Utils#validate_orcid` method returns false for Orcids created within the Sandbox environment. 

```
original_regex = /\A(?:(http|https):\/\/(www\.)?orcid\.org\/)?(\d{4}[[:space:]-]\d{4}[[:space:]-]\d{4}[[:space:]-]\d{3}[0
-9X]+)\z/
original_regex.match?("https://sandbox.orcid.org/0000-0003-0652-4625")
=> false
original_regex.match?("https://orcid.org/0000-0003-0652-4625")
=> true

# New Regex from PR#121
new_regex = /\A(?:(?:http|https):\/\/(?:(?:www|sandbox)?\.)?orcid\.org\/)?(\d{4}[[:space:]-]\d{4}[[:space:]-]\d{4}[[:space:]-]\d{3}[0-9X]+)\z/
new_regex.match?("https://sandbox.orcid.org/0000-0003-0652-4625")
=> true
new_regex.match?("https://orcid.org/0000-0003-0652-4625")
=> true
new_regex.match?("0000-0003-0652-4625")
=> true

```

Here is a PR that amends the Regex to allow the "sandbox" subdomain in the URLs: https://github.com/datacite/bolognese/pull/121

**Comment by kjgarza** [comment]
It might help to include who would use this feature/change and for which use case.

**Comment by prdanelli** [comment]
Hello @kjgarza thank you for replying. 

The use case that I currently have, is that i'm working on developing an Orcid integration, which means I am currently working within their Sandbox environment. However, when passing legitimate sandbox Orcid IDs inside a `contributor` hash into Bolgnese they are returned `nil` because of the "sandbox" subdomain. 

This small change in the PR, means that anyone working on developing a feature/gem can be assured that the data returned from development/testing or in production will be the same.

**Comment by prdanelli** [comment]
@kjgarza Do you think the PR that I added here #121, is ok to merge?

**Comment by richardhallett** [comment]
Thanks for the PR, yes that all seems to make sense.
There will probably be a tagged release of the gem version shortly, there are a couple of other things I am looking at first however.
