### ISSUE TITLE
How to use "bolognese help [COMMAND]"? 

### ISSUE THREAD

**Issue by atmodatcode** [datacite/bolognese#129]
Hello, 

I would very much appreciate it if you could add an example on how to use the help function
"bolognese help [COMMAND]"   # Describe available commands or one specific command.
What can be added as COMMAND?

Thanks a lot and best regards
Angelika

**Comment by digitaldogsbody** [comment]
Hi Angelika,

Currently bolognese has one function, which is called `convert`, and this is run by default when you invoke the bolognese executable. You can get the inline help for this command with `bolognese help convert`, and refer to the [README](https://github.com/datacite/bolognese/blob/master/README.md) file for examples of the format strings that can be supplied as arguments.

Hope this helps :)
Mike

**Comment by atmodatcode** [comment]
Thanks a lot. This answers my question. Regards Angelika
