### ISSUE TITLE
Support Crossref types in DataCite metadata

### ISSUE THREAD

**Issue by mfenner** [datacite/bolognese#25]
https://api.crossref.org/types

**Comment by Repositorian** [comment]
There might be unattended consequences of simply adopting the CrossRef type = dissertation: 
1. the term doctoral thesis is also used as a semantic equivalent
2. A broader term e.g., 'Thesis' would include other student theses including senior, Master's level, as well as doctoral level works that are not related to a PhD but another type of final output (e.g., Doctor of Engineering). 
3. To map to other open citation data for student theses, perhaps a survey of NDLTD, ProQuest, and DCMI vocabs would be informative. Would you like help with this?
