### ISSUE TITLE
Use most recent codemeta spec

### ISSUE THREAD

**Issue by mfenner** [datacite/bolognese#30]
https://raw.githubusercontent.com/codemeta/codemeta/2.0/codemeta.jsonld

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_bz7n)

**Comment by kjgarza** [comment]
### Expected Behaviour


??????

### Current Behaviour


### Steps to Reproduce




### Context (Environment)






### Hypothesis



### Detailed Description


### Possible Implementation

**Comment by kjgarza** [comment]
- [ ]  change writer to produce lastest version of codemeta
- [ ] parametrise reader to read codemeta version 1 and version 2
