### ISSUE TITLE
Title field of DOI 10.1104/pp.111.178582

### ISSUE THREAD

**Issue by flange-ipb** [datacite/bolognese#31]
Some article titles have italic type, for instance for some biological or chemical nomenclature. It seems most publishers do not translate that into the DOI metadata.
Meanwhile I found an exception, https://doi.org/10.1104/pp.111.178582. The Crossref metadata already looks creepy (https://api.crossref.org/v1/works/http://dx.doi.org/10.1104/pp.111.178582). Bolognese returns `"name": "\n              Ectopic Expression of\n              \n              in\n              \n              : Creating a Metabolic Sink Has Tissue-Specific Consequences for the Jasmonate Metabolic Network and Silences Downstream Gene Expression\n            "` (note the missing "AtJMT" and "Nicotiana attenuata"). It would be cool to get the complete title without the newlines and the spaces.

**Comment by mfenner** [comment]
Yes, cleaning up the whitespace makes sense. I don't understand how this relates to *italic* in titles, though.

**Comment by flange-ipb** [comment]
Ok, granted. It's not directly related to italic type. I was specifically looking for such article titles and discovered this issue. Other examples are 10.15252/embj.201797159, 10.1111/tpj.13797 and 10.1104/pp.18.00175. This is really bad practice of these publishers and bolognese should not try to correct it (in contrast to what I said yesterday) - it should pass the title from the crossref metadata. What persists is the problem of missing words and the whitespaces. :)
