### ISSUE TITLE
No matching global declaration available for the validation root

### ISSUE THREAD

**Issue by mfenner** [datacite/bolognese#42]
XML parsing error. The bug is triggered if there is no xmlns for schema 4: `xmlns="http://datacite.org/schema/kernel-4"`, so the following namespaces generate an error:

* http://datacite.org/schema/kernel-2.2
* http://datacite.org/schema/kernel-3
* http://datacite.org/schema/kernel-4.0
http://datacite.org/schema/kernel-4.1

**Comment by kcondon** [comment]
@mfenner,
We're seeing this exception when going to https://mds.test.datacite.org on some but not all of our test boxes. We noticed it 2 days ago. Would this issue account for that? Is there anything we can do to work around it or should we wait for a fix?

**Comment by mfenner** [comment]
This has been fixed. Please let us know if you still have issues with this.
