### ISSUE TITLE
doi_utils.rb:6:in `match': no implicit conversion of Array into String (TypeError)

### ISSUE THREAD

**Issue by hrzepa** [datacite/bolognese#69]
I have followed the instructions at https://github.com/datacite/bolognese (MacOS, Mojave) and now get 

$bolognese --version
1.3.8

which looks good.  But when I provide a .ris file I get the following errors

$bolognese Endnote_thesis_library.ris
/Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/lib/bolognese/doi_utils.rb:6:in `match': no implicit conversion of Array into String (TypeError)
	from /Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/lib/bolognese/doi_utils.rb:6:in `validate_doi'
	from /Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/lib/bolognese/doi_utils.rb:35:in `normalize_doi'
	from /Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/lib/bolognese/readers/ris_reader.rb:50:in `read_ris'
	from /Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/lib/bolognese/metadata.rb:119:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/lib/bolognese/cli.rb:33:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/lib/bolognese/cli.rb:33:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/bolognese-1.3.8/bin/bolognese:6:in `<top (required)>'
	from /usr/local/bin/bolognese:22:in `load'
	from /usr/local/bin/bolognese:22:in `<main>'

Can anyone tell if the error is caused by the  RIS file itself, or my build of  ruby/bolognese ?
[Endnote_thesis_library.ris.txt](https://github.com/datacite/bolognese/files/3453057/Endnote_thesis_library.ris.txt)

**Comment by mfenner** [comment]
@hrzepa bolognese is built to convert metadata for single records, and your RIS file contains a list of records.

Do you see this as an import feature we should add?

**Comment by hrzepa** [comment]
Oh yes please.  We want to process all the bibliographic records for a PhD thesis,  often 100s of them, in one thesis deposition workflow.

**Comment by hrzepa** [comment]
I have created a single record ris file.  The following error is now obtained;

$ bolognese single.ris
41:0: ERROR: Element '{http://datacite.org/schema/kernel-4}titles': Missing child element(s). Expected is ( {http://datacite.org/schema/kernel-4}title ).

[single.ris.txt](https://github.com/datacite/bolognese/files/3455134/single.ris.txt)

**Comment by hrzepa** [comment]
I should add that my build of bolognese works fine with a command such as

bolognese https://doi.org/10.14469/hpc/5980 -t datacite

**Comment by mfenner** [comment]
Ok. I have fixed 100s of special cases with bolognese, and will look at `single.ris`. It looks like bolognese expects `T1` rather than `TI` in your example (the latter is usally handled as book title).

**Comment by mfenner** [comment]
I created a separate issue for the new feature of supporting multiple records. #70

**Comment by hrzepa** [comment]
I should explain that the RIS file  I am using was generated using EndNote X8.2 (on MacOS) by  export as RefMan (RIS). The bibliography was created over a three year period by the PhD student from diverse sources (which may account for the variation in tagging). 

I know that many students here use  Mendeley as their reference manager, and I might try to get a few libraries from that source as well.

**Comment by mfenner** [comment]
Don't worry, it is our job to be flexible with the input. We will support `TI`.

**Comment by hrzepa** [comment]
I have identified a useful tool for creating  RIS or BibTex files from citations embedded into a Word  Document using  Mendeley or  Zotero, which  I thought would be useful to include here; https://github.com/rmzelle/ref-extractor

Citations embedded into  Word using  EndNote can be extracted using the built in EndNote tool in Word and the travelling library export feature.

**Comment by mfenner** [comment]
Very cool. Rintze is one of the maintainers of citationstyles.org, so he knows this stuff. You can of course also use a reference manager such as Zotero (or [ZoteroBib](https://zbib.org/)) to generate a list of formatted citations from a RIS or bibtex file.

**Comment by hrzepa** [comment]
The issue our  PhD student identified is that their reference manager (in this case EndNote) had a significant superset of the citations used in the thesis, and it was not easy to select just those actually used in the word document.  It was more convenient to start with the  Word document itself rather than the refman library used to generate the thesis, and then to generate a suitable (travelling) library which could be converted to  RIS from there.

**Comment by mfenner** [comment]
Makes sense. Unless you create a folder in the reference manager with all the references for a particular publication when you start.
