### ISSUE TITLE
Angle <> brackets not converted correctly for DOI title field

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bolognese#77]
### Expected Behaviour

Angle brackets appear correctly in the title of the DOI

### Current Behaviour

For DOI : 10.5281/zenodo.3526563 with title "Introducing Objectification: when is an < object > a < place >?" the angle brackets do not appear correct in Fabrica, DataCite Search and the API https://api.datacite.org/dois/10.5281/zenodo.3526563

nb: the metadata is ok

### Steps to Reproduce

1. https://api.datacite.org/dois/10.5281/zenodo.3526563
2. https://search.datacite.org/works/10.5281/zenodo.3526563

### Context (Environment)

Production

**Comment by mfenner** [comment]
Duplicate of https://github.com/datacite/bracco/issues/198.
