### ISSUE TITLE
implementation details in the schema.org representation of articles

### ISSUE THREAD

**Issue by cboettig** [datacite/bolognese#9]
Hey @mfenner ,

Apologies if this really isn't the right place to discuss this, please direct me if there's a better thread.

I'm really looking for your input on the best implementation of an article citation in schema.org (I know so far it's only DataCite and not CrossRef that offers a schema.org format, but still).

In particular, I'm looking at the examples Schema.Org gives for [ScholarlyArticle](http://schema.org/ScholarlyArticle).  One of the fascinating but also complete nuisance elements of their implementation is the explicit enumeration of `issue` and `volume` through `isPartOf`.  Instead of something you might see in bibliographic formats (say, bibtex or csl) in which `volume` and `issue` would be 'top-level' attributes of an article, they've been careful with the more semantically precise definitions: the article isPartOf an issue with isPartOf a volume of a periodical. 

Similarly, the `datePublished` is given not as a property of the article but as a property of the issue (again perhaps more semantically precise, at least as far as the `publication-print` date (to use the CSL term) is concerned, but not the most convenient or perhaps expected structure.  Also following this structure makes it harder to know what to do with online-only or entries otherwise missing volume/issue data.  

Anyway, I guess these choices make sense, but wanted to get your thoughts. (I do note that schema.org shows two different versions, both of which use `isPartOf`, but the third is less explicit and simply indicates the ScholarlyArticle isPartOf both an PublicationIssue and a PublicationVolume / Periodical ... maybe this third example is the best compromise?)

**Comment by mfenner** [comment]
Excellent point. You see similar issues with DataCite XML and Dublin Core, neither of which have direct support for periodical, volume, issues or pages.

The Bolognese gem handles Crossref DOIs, so you can see how I have implemented ScholarlyArticle, and suggest changes as needed. Use bolognese as command-line or do content negotiation at data.datacite.org. I for example always use datePublished as Property of the ScholarlyArticle.
