### ISSUE TITLE
Correctly parse ISSN for container field

### ISSUE THREAD

**Issue by mfenner** [datacite/bolognese#98]
Example from 10.1007/978-3-642-34922-5_19:

```
{
  "type": "Book Series",
  "title": "Studies in Fuzziness and Soft Computing",
  "identifier": [{
    "media_type": "print",
    "__content__": "1434-9922"
  }, {
    "media_type": "electronic",
    "__content__": "1860-0808"
  }],
  "identifierType": "ISSN"
}
```

**Comment by richardhallett** [comment]
@mfenner Can you expand upon what is not parsing, the original DataCite metadata with an ISSN? If so the example DOI doesn't appear to contain an ISSN.

**Comment by mfenner** [comment]
It is about handling the print and electronic ISSN subtypes.
